### ISSUE TITLE
'InternalSelectableMathState' is missing implementations for these members:

### ISSUE THREAD

**Issue by muradkhan995** [simpleclub-extended/flutter_math_fork#26] opened 2021-12-19 15:53 UTC
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

    package:facebook_audience_network

For solutions, see https://dart.dev/go/unsound-null-safety
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState'
is missing implementations for these members:

    TextSelectionDelegate.copySelection
    TextSelectionDelegate.cutSelection
    TextSelectionDelegate.pasteText
    TextSelectionDelegate.selectAll
    Try to either
    provide an implementation,
    inherit an implementation from a superclass or mixin,
    mark the class as abstract, or
    provide a 'noSuchMethod' implementation.

class InternalSelectableMathState extends State
^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:985:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
void copySelection(SelectionChangedCause cause);
^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:965:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
void cutSelection(SelectionChangedCause cause);
^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:973:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
Future pasteText(SelectionChangedCause cause);
^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:979:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
void selectAll(SelectionChangedCause cause);
^^^^^^^^^
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0 ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:472:9)
#1 JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:152:33)
#2 FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:650:47)

#3 FrontendCompiler.compile (package:frontend_server/frontend_server.dart:558:9)

#4 listenAndCompile. (package:frontend_server/frontend_server.dart:1135:11)

the Dart compiler exited unexpectedly.

**Comment by muradkhan995** [comment] 2021-12-19 17:05
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:facebook_audience_network

For solutions, see https://dart.dev/go/unsound-null-safety
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState'
is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InternalSelectableMathState extends State<InternalSelectableMath>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:985:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:965:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:973:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:979:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:472:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:152:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:650:47)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:558:9)
<asynchronous suspension>
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1135:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.

**Comment by creativecreatorormaybenot** [comment] 2021-12-19 19:29
Duplicate of #7.

**Closed by creativecreatorormaybenot** 2021-12-19 19:29 UTC
