### ISSUE TITLE
Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:

### ISSUE THREAD

**Issue by iamwasimaftab** [simpleclub-extended/flutter_math_fork#22] opened 2021-12-14 14:27 UTC
its flutter project any solution for it???

./../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7:Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:

TextSelectionDelegate.copySelection
TextSelectionDelegate.cutSelection
TextSelectionDelegate.pasteText
TextSelectionDelegate.selectAll
Try to either
provide an implementation,
inherit an implementation from a superclass or mixin,
mark the class as abstract, or
provide a 'noSuchMethod' implementation.

**Comment by creativecreatorormaybenot** [comment] 2021-12-14 15:30
Duplicate of #7. Please update to the latest version of the package.

**Closed by creativecreatorormaybenot** 2021-12-14 15:30 UTC

**Comment by athallahannafis** [comment] 2021-12-14 15:47
I faced that problem too after doing `flutter upgrade` to v2.8.0 (latest). So I decided to downgrade my flutter to 2.5.3 to solve it in my current project.

**Comment by iamwasimaftab** [comment] 2021-12-15 07:32
but i try to upgrade and downgrade both is not working for me and other solution???

**Comment by creativecreatorormaybenot** [comment] 2021-12-15 14:42
@iamwasimaftab Can you confirm that this is occuring with `flutter_math_fork: 0.5.0`? Can you please send the full error message in this case (including the file path)?

**Comment by iamwasimaftab** [comment] 2021-12-15 15:03
@creativecreatorormaybenot 

showing --- flutter_math_fork-0.3.3+1

Cylinder@wasi-Mac-Pro Application % flutter build apk
Running "flutter pub get" in Application...                         3.0s

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InternalSelectableMathState extends State<InternalSelectableMath>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/services/text_input.dart:1034:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/services/text_input.dart:1014:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/services/text_input.dart:1022:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
../../../../flutter/packages/flutter/lib/src/services/text_input.dart:1028:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.0/lib/src/visibility_detector_layer.dart:276:21: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
    super.addToScene(builder, layerOffset);
                    ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/Cylinder/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/Cylinder/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Running Gradle task 'assembleRelease'...                           24.1s
Gradle task assembleRelease failed with exit code 1
Cylinder@wasi-Mac-Pro Application %

**Comment by creativecreatorormaybenot** [comment] 2021-12-15 15:31
@iamwasimaftab you are using an old version of the package `0.3.3`. This has been fixed in `0.5.0`.

**Comment by creativecreatorormaybenot** [comment] 2021-12-15 18:13
@creativecreatorormaybenot `chewie` uses an outdated version of the `provider` package.

**Comment by iamwasimaftab** [comment] 2021-12-15 19:28
How can I upgraded??
It's last version I used it's may be already upgraded

**Comment by creativecreatorormaybenot** [comment] 2021-12-15 22:22
@iamwasimaftab you need to fork it (and create a pull request) or override the dependency.

**Comment by vivekmulani01** [comment] 2021-12-27 08:48
hello bro i have same problem can you help me

**Comment by vivekmulani01** [comment] 2021-12-27 08:53
this is the full error :-
 
Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:
../…/widgets/selectable.dart:407
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InternalSelectableMathState extends State<InternalSelectableMath>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Context: 'TextSelectionDelegate.copySelection' is defined here.
../…/services/text_input.dart:985
  void copySelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^^
: Context: 'TextSelectionDelegate.cutSelection' is defined here.
../…/services/text_input.dart:965
  void cutSelection(SelectionChangedCause cause);
       ^^^^^^^^^^^^
: Context: 'TextSelectionDelegate.pasteText' is defined here.
../…/services/text_input.dart:973
  Future<void> pasteText(SelectionChangedCause cause);
               ^^^^^^^^^
: Context: 'TextSelectionDelegate.selectAll' is defined here.
../…/services/text_input.dart:979
  void selectAll(SelectionChangedCause cause);
       ^^^^^^^^^
: Error: Too many positional arguments: 1 allowed, but 2 found.
../…/src/visibility_detector_layer.dart:276
Try removing the extra positional arguments.
    super.addToScene(builder, layerOffset);
                    ^
3

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\admin\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\admin\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 39s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

what i do bro ?
